added full project
leenmirise/Hacker pull request #1
Opened 2023-06-29 11:30 UTC by leenmirise

2023-06-29 11:45 UTC, leenmirise commented
@heyanniemoran

2023-06-29 13:06 UTC, heyanniemoran reviewed
Нашелся баг. Если я жму дважды на кнопку "show comments" у меня дублируются комменты

![image](https://github.com/leenmirise/Hacker/assets/28657911/849752bf-1262-434f-99ea-b891a6bd2358)

2023-06-29 13:06 UTC, heyanniemoran commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
Скрипты подключаем перед `</body>`.

2023-06-29 13:06 UTC, heyanniemoran commented on index.html
> +            <div class="container-fluid justify-content-between align-items-center">
Не сработают классы `justify-content-between align-items-center`. Сможешь ответить почему?

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +                    card = jQuery(cardText);
`jQuery` -> `$` не сработает?

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +            post.find('#number_comm').text('Number of comm: ' + data.comments_count);
Сможем сократить дублирование кода? Здесь и функции выше одинаковые куски кода.

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +function LoadNews() {
Функции именуем как `loadNews`.

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +    $("#content").load("./components/newsPosts.html");
1. Зачем предварительно очищать `content`?
2. Можно ли как-то сократить запись?

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +                    console.log(post.id);
Не забываем убирать `console.log` и `alert`. В error можешь оставить, но лучше выводить какое-нибудь предупреждение для пользователя.

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +                    post.find('#comments').first().append(CreateCommentCard(cardText, doc, el, false));
1. Может ли у тебя быть несколько элементов `#comments` на странице?
2. `id` - это уникальный идентификатор => он должен быть один на странице. Если у тебя несколько одинаковых по структуре элементов, то привязывайся к классам.

2023-06-29 13:06 UTC, heyanniemoran commented on script.js
> +        doc.parseFromString(element.content, "text/html").documentElement.textContent);
А зачем доставать только текст?

2023-06-29 18:09 UTC, leenmirise commented on index.html
> +            <div class="container-fluid justify-content-between align-items-center">
Может потому что флекса нет?

2023-06-29 21:14 UTC, heyanniemoran commented on index.html
> +            <div class="container-fluid justify-content-between align-items-center">
Правильно. Исправляй.

2023-06-30 07:33 UTC, leenmirise commented on script.js
> +    $("#content").load("./components/newsPosts.html");
1. Видимо думала что старые записи не очистятся, но без этого всё нормально
2. Не знаю, насколько это сокращение, но есть ещё функция empty(), но я решила просто эту строчку убрать

2023-06-30 07:33 UTC, leenmirise commented on script.js
> +        doc.parseFromString(element.content, "text/html").documentElement.textContent);
а что нам еще нужно?

2023-06-30 08:49 UTC, heyanniemoran commented on script.js
> +        doc.parseFromString(element.content, "text/html").documentElement.textContent);
Если смотреть на то, что там приходит можно увидеть, что они там то списки ставят, то еще что-то подобное. Я бы выводила прям то, что выходит.

2023-06-30 12:06 UTC, heyanniemoran commented
Задание не выполнено до конца. Что еще надо:
1. Показывать последние 100 новостей в виде списка, отсортированного по дате, самые свежие сверху. Сейчас 30. 
2. На странице новости должна быть кнопка для возврата к списку новостей

2023-06-30 12:22 UTC, heyanniemoran requested changes

2023-06-30 12:22 UTC, heyanniemoran commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
Мимо. Перед закрывающим тегом.

2023-06-30 12:22 UTC, heyanniemoran commented on components/card.html
> +                    <p class="text-muted author" id="author">By AUTHOR</p>
Почти. Надо убрать id

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
> +            post.find('.url').attr('href', data.url);
Можно объединить `post.find('.url').text(data.url).attr('href', data.url)`

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
> +function loadOneNews() {
Я бы поменяла на `loadNewsItem`

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
>                      $("main").append(card);
Нежелательно привязываться к конкретным тегам, лучше к классам.

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
> +    return true;
Не нужен

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
> +    return true;
Не нужен

2023-06-30 12:22 UTC, heyanniemoran commented on script.js
> +    return true;
Не нужен

2023-06-30 14:06 UTC, leenmirise commented
> Задание не выполнено до конца. Что еще надо: Показывать последние 100 новостей в виде списка, отсортированного по дате, самые свежие сверху. Сейчас 30.

https://api.hnpwa.com/v0/news/1.json
в этой апишке всего 30 новостей

2023-07-07 13:16 UTC, heyanniemoran commented
Проверила у себя локально, всё ок (локально ок работает, а в github pages не совсем так). В codesandbox не экспортили.

2023-07-12 07:36 UTC, merged

2023-07-26 10:00 UTC, crutch12 commented on script.js
> +    $("#content").load("./components/newsPosts.html");
Очень простая реализация через jquery
Есть понимание, как то же самое сделать через `fetch` + работу с DOM?

2023-07-26 10:02 UTC, crutch12 commented on script.js
> +$(document).ready(() => {
В реальных проектах у нас вообще не используется jquery, даже зависимости такой нет
Лучше подписываться через document чистым js'ом

2023-07-26 10:20 UTC, crutch12 commented
Молодец

2023-07-26 12:50 UTC, leenmirise commented on script.js
> +    $("#content").load("./components/newsPosts.html");
В теории понимание есть, с DOM работала, как работает fetch тоже понимаю